// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6VDKx5-zWnQn5_XSuDWSCk5eeSM3UYAY',
    appId: '1:263530933357:web:26cdf47211074943916364',
    messagingSenderId: '263530933357',
    projectId: 'online-education-6256a',
    authDomain: 'online-education-6256a.firebaseapp.com',
    databaseURL: 'https://online-education-6256a-default-rtdb.firebaseio.com',
    storageBucket: 'online-education-6256a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpqfEkPXPk0APVc_bLEyce3wd0PK0hjUs',
    appId: '1:263530933357:android:defc95e8db08b4a1916364',
    messagingSenderId: '263530933357',
    projectId: 'online-education-6256a',
    databaseURL: 'https://online-education-6256a-default-rtdb.firebaseio.com',
    storageBucket: 'online-education-6256a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAveEgIAIrxw7ZAtDacwL1FrykxSe1Ckz0',
    appId: '1:263530933357:ios:0ec862da03aff155916364',
    messagingSenderId: '263530933357',
    projectId: 'online-education-6256a',
    databaseURL: 'https://online-education-6256a-default-rtdb.firebaseio.com',
    storageBucket: 'online-education-6256a.appspot.com',
    iosBundleId: 'com.example.firebaseQuiz',
  );
}
